version: "3.8"

networks:
  default:
    name: ${APP_NAME}-network

services:
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:5.7 # For Apple M1 chip, use mariadb
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306"
    volumes:
      - ./docker/mysql/data:/docker-entrypoint-initdb.d:rw

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 7171:80
    volumes:
      - /sessions
    logging:
      driver: none
    links:
      - mysql

  wordpress:
    container_name: ${APP_NAME}-wordpress
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile.local
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      URL_SITE: ${URL_SITE}
      XDEBUG_CONFIG: remote_host=172.20.0.4
      PHP_XDEBUG_ENABLED: 1ss
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    links:
      - mysql
    volumes:
      - ./src:/var/www/html/

  nginx-proxy:
    depends_on:
      - wordpress
    container_name: ${APP_NAME}-nginx-proxy
    hostname: nginx-proxy
    build:
      dockerfile: ./docker/nginx-proxy/Dockerfile.local
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    links:
      - wordpress
